export const WORDS = [
  // ── 3級 ──
  { id: 1,  en: 'species',     ja: '種、種類',     level: '3',    ex: 'There are many species of birds in this forest.',           exja: 'この森にはたくさんの種類の鳥がいます。' },
  { id: 2,  en: 'ancient',     ja: '古代の',       level: '3',    ex: 'We visited an ancient temple in Kyoto.',                    exja: '私たちは京都の古代の寺を訪れました。' },
  { id: 3,  en: 'celebrate',   ja: '祝う',         level: '3',    ex: 'We celebrate New Year with our family.',                    exja: '私たちは家族と一緒に新年を祝います。' },
  { id: 4,  en: 'communicate', ja: '伝える、連絡する', level: '3', ex: 'It is important to communicate clearly.',                  exja: '明確に伝えることが大切です。' },
  { id: 5,  en: 'describe',    ja: '説明する',     level: '3',    ex: 'Can you describe what you saw?',                           exja: '見たものを説明できますか？' },
  { id: 6,  en: 'discover',    ja: '発見する',     level: '3',    ex: 'Scientists discover new planets every year.',               exja: '科学者は毎年新しい惑星を発見します。' },
  { id: 7,  en: 'education',   ja: '教育',         level: '3',    ex: 'Education is important for a better future.',               exja: 'より良い未来のために教育は大切です。' },
  { id: 8,  en: 'encourage',   ja: '励ます',       level: '3',    ex: 'My teacher always encourages me to try my best.',          exja: '先生はいつも最善を尽くすよう励ましてくれます。' },
  { id: 9,  en: 'environment', ja: '環境',         level: '3',    ex: 'We must protect the environment for future generations.',   exja: '未来の世代のために環境を守らなければなりません。' },
  { id: 10, en: 'experience',  ja: '経験、体験',   level: '3',    ex: 'Studying abroad was a great experience.',                   exja: '留学はすばらしい経験でした。' },
  { id: 11, en: 'foreign',     ja: '外国の',       level: '3',    ex: 'She can speak three foreign languages.',                    exja: '彼女は3つの外国語を話せます。' },
  { id: 12, en: 'improve',     ja: '改善する',     level: '3',    ex: 'Practice every day to improve your English.',               exja: '英語を上達させるために毎日練習しましょう。' },
  { id: 13, en: 'language',    ja: '言語',         level: '3',    ex: 'English is the most widely spoken language in the world.',  exja: '英語は世界で最も広く話されている言語です。' },
  { id: 14, en: 'natural',     ja: '自然の',       level: '3',    ex: 'The park is full of natural beauty.',                       exja: 'その公園は自然の美しさにあふれています。' },
  { id: 15, en: 'protect',     ja: '守る、保護する', level: '3',  ex: 'We should protect endangered animals.',                    exja: '絶滅危惧動物を守るべきです。' },
  { id: 16, en: 'realize',     ja: '気づく、実現する', level: '3', ex: 'I realized that I had left my bag on the train.',         exja: '電車にかばんを忘れてきたと気づきました。' },
  { id: 17, en: 'tradition',   ja: '伝統',         level: '3',    ex: 'Wearing a kimono is a Japanese tradition.',                 exja: '着物を着ることは日本の伝統です。' },
  { id: 18, en: 'participate', ja: '参加する',     level: '3',    ex: 'All students are asked to participate in the event.',       exja: '全生徒がそのイベントに参加するよう求められています。' },
  { id: 19, en: 'produce',     ja: '生産する、作る', level: '3',  ex: 'This factory produces thousands of cars a day.',            exja: 'この工場は1日に何千台もの車を生産します。' },
  { id: 20, en: 'result',      ja: '結果',         level: '3',    ex: 'The result of the test surprised everyone.',                exja: 'テストの結果は全員を驚かせました。' },

  // ── 準2級 ──
  { id: 21, en: 'accomplish',  ja: '達成する',     level: 'pre2', ex: 'She accomplished her goal of running a marathon.',         exja: '彼女はマラソン完走という目標を達成しました。' },
  { id: 22, en: 'appropriate', ja: '適切な',       level: 'pre2', ex: 'Please use appropriate language in class.',                exja: '授業では適切な言葉遣いをしてください。' },
  { id: 23, en: 'attitude',    ja: '態度、姿勢',   level: 'pre2', ex: 'His positive attitude helped him succeed.',                exja: '彼の前向きな姿勢が成功を助けました。' },
  { id: 24, en: 'avoid',       ja: '避ける',       level: 'pre2', ex: 'Try to avoid eating too much sugar.',                      exja: '糖分の摂り過ぎを避けましょう。' },
  { id: 25, en: 'benefit',     ja: '利益、恩恵',   level: 'pre2', ex: 'Exercise has many benefits for your health.',              exja: '運動は健康に多くの恩恵をもたらします。' },
  { id: 26, en: 'conflict',    ja: '衝突、対立',   level: 'pre2', ex: 'The two countries had a conflict over land.',              exja: '両国は土地をめぐって対立しました。' },
  { id: 27, en: 'creative',    ja: '創造的な',     level: 'pre2', ex: 'The students came up with creative solutions.',            exja: '生徒たちは創造的な解決策を考え出しました。' },
  { id: 28, en: 'develop',     ja: '発達する、開発する', level: 'pre2', ex: 'Children develop language skills naturally.',        exja: '子どもたちは自然に言語能力を発達させます。' },
  { id: 29, en: 'effective',   ja: '効果的な',     level: 'pre2', ex: 'Regular review is an effective study method.',             exja: '定期的な復習は効果的な学習方法です。' },
  { id: 30, en: 'establish',   ja: '設立する、確立する', level: 'pre2', ex: 'The school was established over 100 years ago.',    exja: 'その学校は100年以上前に設立されました。' },
  { id: 31, en: 'evidence',    ja: '証拠',         level: 'pre2', ex: 'There is no evidence that he was there.',                  exja: '彼がそこにいたという証拠はありません。' },
  { id: 32, en: 'expand',      ja: '拡大する、広げる', level: 'pre2', ex: 'The company plans to expand its business overseas.',  exja: '会社は海外にビジネスを拡大する計画です。' },
  { id: 33, en: 'global',      ja: '地球規模の',   level: 'pre2', ex: 'Climate change is a global problem.',                      exja: '気候変動は地球規模の問題です。' },
  { id: 34, en: 'influence',   ja: '影響',         level: 'pre2', ex: 'Social media has a big influence on young people.',        exja: 'SNSは若者に大きな影響を与えています。' },
  { id: 35, en: 'maintain',    ja: '維持する',     level: 'pre2', ex: 'It is hard to maintain a healthy lifestyle.',              exja: '健康的な生活習慣を維持するのは難しいです。' },
  { id: 36, en: 'opportunity', ja: '機会',         level: 'pre2', ex: 'Studying abroad is a great opportunity to grow.',          exja: '留学は成長する素晴らしい機会です。' },
  { id: 37, en: 'pollution',   ja: '汚染',         level: 'pre2', ex: 'Air pollution is a serious problem in big cities.',        exja: '大気汚染は大都市での深刻な問題です。' },
  { id: 38, en: 'reduce',      ja: '減らす',       level: 'pre2', ex: 'We need to reduce our use of plastic.',                    exja: 'プラスチックの使用を減らす必要があります。' },
  { id: 39, en: 'society',     ja: '社会',         level: 'pre2', ex: 'Technology plays an important role in modern society.',    exja: 'テクノロジーは現代社会で重要な役割を果たしています。' },
  { id: 40, en: 'volunteer',   ja: 'ボランティア活動をする', level: 'pre2', ex: 'Many students volunteer at local events.',    exja: '多くの生徒が地域のイベントでボランティアをしています。' },

  // ── 2級 ──
  { id: 41, en: 'advocate',    ja: '主張する、支持者', level: '2', ex: 'She advocates for equal rights for all people.',         exja: '彼女はすべての人の平等な権利を主張します。' },
  { id: 42, en: 'consequence', ja: '結果、影響',   level: '2',    ex: 'We must think about the consequences of our actions.',    exja: '自分の行動の結果について考えなければなりません。' },
  { id: 43, en: 'contemporary',ja: '現代の',       level: '2',    ex: 'She studies contemporary art at university.',              exja: '彼女は大学で現代アートを研究しています。' },
  { id: 44, en: 'contribute',  ja: '貢献する',     level: '2',    ex: 'Everyone can contribute to protecting the environment.',  exja: '誰もが環境保護に貢献できます。' },
  { id: 45, en: 'diverse',     ja: '多様な',       level: '2',    ex: 'Japan has a diverse range of traditional foods.',          exja: '日本には多様な伝統食があります。' },
  { id: 46, en: 'eliminate',   ja: '取り除く',     level: '2',    ex: 'The goal is to eliminate poverty worldwide.',              exja: '目標は世界中の貧困を取り除くことです。' },
  { id: 47, en: 'emphasize',   ja: '強調する',     level: '2',    ex: 'The teacher emphasized the importance of reading.',        exja: '先生は読書の重要性を強調しました。' },
  { id: 48, en: 'generate',    ja: '生み出す、発生させる', level: '2', ex: 'Solar panels generate electricity from sunlight.',   exja: 'ソーラーパネルは太陽光から電力を生み出します。' },
  { id: 49, en: 'implement',   ja: '実施する',     level: '2',    ex: 'The government plans to implement new policies.',          exja: '政府は新しい政策を実施する計画です。' },
  { id: 50, en: 'inevitable',  ja: '避けられない', level: '2',    ex: 'Change is inevitable in today\'s fast-moving world.',     exja: '急速に変化する現代社会では変化は避けられません。' },
  { id: 51, en: 'investigate', ja: '調査する',     level: '2',    ex: 'Police are investigating the cause of the accident.',     exja: '警察は事故の原因を調査しています。' },
  { id: 52, en: 'modify',      ja: '修正する',     level: '2',    ex: 'We may need to modify our plans.',                        exja: '計画を修正する必要があるかもしれません。' },
  { id: 53, en: 'perspective', ja: '視点、観点',   level: '2',    ex: 'Try to see things from a different perspective.',         exja: '物事を別の視点から見るようにしてみましょう。' },
  { id: 54, en: 'significant', ja: '重大な、著しい', level: '2',  ex: 'There has been a significant increase in online shopping.',exja: 'オンラインショッピングが著しく増加しています。' },
  { id: 55, en: 'sufficient',  ja: '十分な',       level: '2',    ex: 'Eight hours of sleep is sufficient for most adults.',     exja: '8時間の睡眠はほとんどの大人に十分です。' },
  { id: 56, en: 'sustainable', ja: '持続可能な',   level: '2',    ex: 'We need to find sustainable sources of energy.',          exja: '持続可能なエネルギー源を見つける必要があります。' },
  { id: 57, en: 'whereas',     ja: '一方で',       level: '2',    ex: 'I like coffee, whereas my sister prefers tea.',            exja: '私はコーヒーが好きですが、姉はお茶が好きです。' },
  { id: 58, en: 'acknowledge', ja: '認める',       level: '2',    ex: 'He acknowledged that he had made a mistake.',             exja: '彼は間違いを犯したことを認めました。' },
  { id: 59, en: 'contradict',  ja: '矛盾する',     level: '2',    ex: 'His actions contradict what he said earlier.',            exja: '彼の行動は以前言ったことと矛盾しています。' },
  { id: 60, en: 'regardless',  ja: '〜にかかわらず', level: '2',  ex: 'We will proceed regardless of the weather.',              exja: '天気にかかわらず、私たちは進めます。' },

  // ── 準1級 ──
  { id: 61, en: 'alleviate',   ja: '軽減する',     level: 'pre1', ex: 'This medicine can alleviate your pain.',                  exja: 'この薬はあなたの痛みを軽減できます。' },
  { id: 62, en: 'ambiguous',   ja: 'あいまいな',   level: 'pre1', ex: 'The instructions were ambiguous and hard to follow.',     exja: '指示があいまいで従うのが難しかった。' },
  { id: 63, en: 'autonomous',  ja: '自律的な',     level: 'pre1', ex: 'Autonomous vehicles can drive without a human driver.',   exja: '自律走行車は人間の運転なしで走ることができます。' },
  { id: 64, en: 'coherent',    ja: '一貫した',     level: 'pre1', ex: 'Please write a coherent essay with a clear argument.',    exja: '明確な主張のある一貫した文章を書いてください。' },
  { id: 65, en: 'contemplate', ja: '熟考する',     level: 'pre1', ex: 'She sat quietly and contemplated her future.',            exja: '彼女は静かに座って自分の将来を熟考しました。' },
  { id: 66, en: 'exacerbate',  ja: '悪化させる',   level: 'pre1', ex: 'Stress can exacerbate many health conditions.',           exja: 'ストレスは多くの健康状態を悪化させることがあります。' },
  { id: 67, en: 'facilitate',  ja: '促進する、容易にする', level: 'pre1', ex: 'Technology facilitates communication across borders.', exja: 'テクノロジーは国境を越えたコミュニケーションを促進します。' },
  { id: 68, en: 'hypothetical',ja: '仮説の',       level: 'pre1', ex: 'Let\'s consider a hypothetical situation.',               exja: '仮説的な状況を考えてみましょう。' },
  { id: 69, en: 'imminent',    ja: '差し迫った',   level: 'pre1', ex: 'A typhoon is imminent, so we must prepare.',              exja: '台風が差し迫っているので準備しなければなりません。' },
  { id: 70, en: 'meticulous',  ja: '細心の、几帳面な', level: 'pre1', ex: 'She is meticulous in her work and rarely makes errors.', exja: '彼女は仕事に細心で、めったにミスをしません。' },
  { id: 71, en: 'nuance',      ja: '微妙な違い、ニュアンス', level: 'pre1', ex: 'Translation often loses the nuance of the original text.', exja: '翻訳では原文のニュアンスが失われることがよくあります。' },
  { id: 72, en: 'perpetuate',  ja: '永続させる',   level: 'pre1', ex: 'These stories perpetuate harmful stereotypes.',            exja: 'これらの話は有害なステレオタイプを永続させます。' },
  { id: 73, en: 'pragmatic',   ja: '実用的な',     level: 'pre1', ex: 'We need a pragmatic solution to this problem.',            exja: 'この問題には実用的な解決策が必要です。' },
  { id: 74, en: 'scrutinize',  ja: '詳しく調べる', level: 'pre1', ex: 'Experts scrutinize every detail of the plan.',             exja: '専門家たちは計画のあらゆる詳細を詳しく調べます。' },
  { id: 75, en: 'versatile',   ja: '多才な、多目的な', level: 'pre1', ex: 'She is a versatile artist who can paint, sing, and dance.', exja: '彼女は絵を描き、歌い、踊ることができる多才な芸術家です。' },
  { id: 76, en: 'profound',    ja: '深遠な、深い', level: 'pre1', ex: 'Her speech had a profound effect on the audience.',        exja: '彼女のスピーチは聴衆に深い影響を与えました。' },
  { id: 77, en: 'concede',     ja: '認める、譲歩する', level: 'pre1', ex: 'He finally conceded that he was wrong.',               exja: '彼はついに自分が間違っていたと認めました。' },
];
